---
Name: algoliasearch
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - Marcz\Algolia\AlgoliaAdminExtension

Marcz\Search\Processor\Exporter:
  extensions:
    - Marcz\Algolia\Extensions\Exporter